// ignore_for_file: avoid_print
//
// Stereo WAV integration tests for OfflineAnalyzer._parseWav.
//
// These tests load synthetic stereo WAV files generated by
//   scripts/generate_test_wavs.py  (STEREO_CASES list)
// and verify that OfflineAnalyzer.analyzeWav() decodes them correctly via
// the production stereo-downmix path.
//
// ── Why these tests matter ─────────────────────────────────────────────────
//
// Without the stereo downmix fix, a 2-channel interleaved WAV is read as if
// it were a mono stream with twice as many samples.  This doubles the apparent
// frame count, halves every timing measurement, and causes the decoder to see
// only noise → empty or garbage output.
//
// The fix in _parseWav (offline_analyzer.dart) averages all channels per
// sample frame.  These tests would fail immediately if that logic regresses.
//
// ── File layout ───────────────────────────────────────────────────────────
//
//  scripts/test_wavs/script_generated_wavs/stereo_*.wav
//    — 27 stereo WAV files in four groups:
//        1. Clean 44100 Hz, both channels (L+R)        [baseline]
//        2. Non-standard tone frequencies (600 / 800 Hz)
//        3. Noisy stereo (20 dB / 10 dB SNR)
//        4. 48 kHz stereo (YouTube / device recording format)
//        5. Asymmetric channels (signal in L only, or R only)
//
// ── Test strategy ─────────────────────────────────────────────────────────
//
//  • Exact-match tests (clean signals, ≥ 20 dB SNR): decoded text == expected.
//  • Non-empty tests (heavy noise): decoder produces something non-empty.
//  • Equivalence tests: stereo L+R WAV decodes identically to its mono twin.

import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:morse_comms/core/dsp/offline_analyzer.dart';

const _dir = 'scripts/test_wavs/script_generated_wavs';

String _norm(String s) => s.trim().replaceAll(RegExp(r'\s+'), ' ');

/// Decode a WAV file at [path] using [targetFrequencyHz] and return
/// normalised text.  Skips (returns null) when the file does not exist so
/// tests are skipped gracefully without breaking CI if generation was skipped.
String? _decode(String path, {double targetFrequencyHz = 700.0}) {
  final file = File(path);
  if (!file.existsSync()) {
    print('  [SKIP] file not found: $path');
    return null;
  }
  final bytes = Uint8List.fromList(file.readAsBytesSync());
  final result = OfflineAnalyzer.analyzeWav(bytes,
      targetFrequencyHz: targetFrequencyHz);
  return _norm(result);
}

void main() {
  // ══════════════════════════════════════════════════════════════════════════
  // 1.  Clean stereo 44100 Hz — both channels (L+R)
  //
  //     The decoder must produce an exact match, because the signal is clean
  //     and the stereo downmix is a simple average of identical L+R samples.
  // ══════════════════════════════════════════════════════════════════════════
  group('Stereo WAV — clean 44100 Hz L+R (exact match)', () {
    const cases = <String, String>{
      'stereo_sos_10wpm':         'SOS',
      'stereo_sos_15wpm':         'SOS',
      'stereo_sos_20wpm':         'SOS',
      'stereo_sos_25wpm':         'SOS',
      'stereo_sos_30wpm':         'SOS',
      'stereo_paris_20wpm':       'PARIS',
      'stereo_hello_world_15wpm': 'HELLO WORLD',
      'stereo_cq_cq_20wpm':       'CQ CQ',
    };

    for (final entry in cases.entries) {
      test('${entry.key} → "${entry.value}"', () {
        final result = _decode('$_dir/${entry.key}.wav');
        if (result == null) return; // file absent — skip
        print('  ${entry.key} → "$result"');
        expect(result, entry.value,
            reason: 'Stereo L+R 44100 Hz clean WAV must decode exactly');
      });
    }
  });

  // ══════════════════════════════════════════════════════════════════════════
  // 2.  Non-standard tone frequencies, stereo
  //
  //     The Goertzel detector must be pointed at the correct frequency.
  //     Tests pass targetFrequencyHz matching the WAV's tone.
  // ══════════════════════════════════════════════════════════════════════════
  group('Stereo WAV — non-standard frequencies', () {
    test('stereo_sos_20wpm_600hz decodes at 600 Hz', () {
      final r = _decode('$_dir/stereo_sos_20wpm_600hz.wav',
          targetFrequencyHz: 600.0);
      if (r == null) return;
      print('  sos 600 Hz stereo → "$r"');
      expect(r, 'SOS');
    });

    test('stereo_sos_20wpm_800hz decodes at 800 Hz', () {
      final r = _decode('$_dir/stereo_sos_20wpm_800hz.wav',
          targetFrequencyHz: 800.0);
      if (r == null) return;
      print('  sos 800 Hz stereo → "$r"');
      expect(r, 'SOS');
    });

    test('stereo_paris_20wpm_600hz decodes at 600 Hz', () {
      final r = _decode('$_dir/stereo_paris_20wpm_600hz.wav',
          targetFrequencyHz: 600.0);
      if (r == null) return;
      print('  paris 600 Hz stereo → "$r"');
      expect(r, 'PARIS');
    });

    test('decoding 600 Hz file at wrong 700 Hz target gives fewer useful chars', () {
      final at600 = _decode('$_dir/stereo_sos_20wpm_600hz.wav',
          targetFrequencyHz: 600.0);
      final at700 = _decode('$_dir/stereo_sos_20wpm_600hz.wav',
          targetFrequencyHz: 700.0);
      if (at600 == null || at700 == null) return;
      final useful600 =
          at600.replaceAll('?', '').replaceAll(' ', '').length;
      final useful700 =
          at700.replaceAll('?', '').replaceAll(' ', '').length;
      print('  600 Hz file: @600Hz useful=$useful600  @700Hz useful=$useful700');
      expect(useful600, greaterThanOrEqualTo(useful700),
          reason: 'Correct target frequency must decode at least as well');
    });
  });

  // ══════════════════════════════════════════════════════════════════════════
  // 3.  Noisy stereo
  //
  //     20 dB SNR: expect exact match (noise well above decoder threshold).
  //     10 dB SNR: expect non-empty (decoder still finds some signal).
  // ══════════════════════════════════════════════════════════════════════════
  group('Stereo WAV — noise tolerance', () {
    test('stereo_sos_20wpm_20db (20 dB SNR) decodes exactly', () {
      final r = _decode('$_dir/stereo_sos_20wpm_20db.wav');
      if (r == null) return;
      print('  sos 20 dB stereo → "$r"');
      expect(r, 'SOS');
    });

    test('stereo_paris_20wpm_20db (20 dB SNR) decodes exactly', () {
      final r = _decode('$_dir/stereo_paris_20wpm_20db.wav');
      if (r == null) return;
      print('  paris 20 dB stereo → "$r"');
      expect(r, 'PARIS');
    });

    test('stereo_sos_30wpm_20db (20 dB SNR) decodes exactly', () {
      final r = _decode('$_dir/stereo_sos_30wpm_20db.wav');
      if (r == null) return;
      print('  sos 30wpm 20 dB stereo → "$r"');
      expect(r, 'SOS');
    });

    test('stereo_sos_20wpm_10db (10 dB SNR) produces non-empty output', () {
      final r = _decode('$_dir/stereo_sos_20wpm_10db.wav');
      if (r == null) return;
      print('  sos 10 dB stereo → "$r"');
      expect(r, isNot(isEmpty),
          reason: 'Decoder must produce output even at heavy noise');
    });
  });

  // ══════════════════════════════════════════════════════════════════════════
  // 4.  48 kHz stereo (YouTube / Android device recording format)
  //
  //     The WAV header carries sample_rate=48000; _parseWav must read this
  //     and pass it through to the GoertzelDetector so frame timings are
  //     computed at 48 kHz, not 44.1 kHz.
  // ══════════════════════════════════════════════════════════════════════════
  group('Stereo WAV — 48 kHz sample rate', () {
    test('stereo_sos_20wpm_48k decodes exactly', () {
      final r = _decode('$_dir/stereo_sos_20wpm_48k.wav');
      if (r == null) return;
      print('  sos 20wpm 48k stereo → "$r"');
      expect(r, 'SOS');
    });

    test('stereo_sos_10wpm_48k decodes exactly', () {
      final r = _decode('$_dir/stereo_sos_10wpm_48k.wav');
      if (r == null) return;
      print('  sos 10wpm 48k stereo → "$r"');
      expect(r, 'SOS');
    });

    test('stereo_sos_30wpm_48k decodes exactly', () {
      final r = _decode('$_dir/stereo_sos_30wpm_48k.wav');
      if (r == null) return;
      print('  sos 30wpm 48k stereo → "$r"');
      expect(r, 'SOS');
    });

    test('stereo_paris_20wpm_48k decodes exactly', () {
      final r = _decode('$_dir/stereo_paris_20wpm_48k.wav');
      if (r == null) return;
      print('  paris 20wpm 48k stereo → "$r"');
      expect(r, 'PARIS');
    });

    test('stereo_hello_world_48k decodes exactly', () {
      final r = _decode('$_dir/stereo_hello_world_48k.wav');
      if (r == null) return;
      print('  hello world 48k stereo → "$r"');
      expect(r, 'HELLO WORLD');
    });

    test('stereo_sos_20wpm_48k_20db (48 kHz, 20 dB SNR) decodes exactly', () {
      final r = _decode('$_dir/stereo_sos_20wpm_48k_20db.wav');
      if (r == null) return;
      print('  sos 48k 20dB stereo → "$r"');
      expect(r, 'SOS');
    });
  });

  // ══════════════════════════════════════════════════════════════════════════
  // 5.  Asymmetric channels: signal in L only, or R only
  //
  //     After downmixing, mono[i] = signal[i] / 2 (amplitude halved).
  //     The silence frames remain at 0, so SNR is unchanged — the decoder
  //     should still produce an exact match.
  //
  //     This exercises the channel-averaging loop for non-identical channels.
  // ══════════════════════════════════════════════════════════════════════════
  group('Stereo WAV — asymmetric channels (L-only and R-only)', () {
    test('stereo_sos_20wpm_left (L channel only) decodes exactly', () {
      final r = _decode('$_dir/stereo_sos_20wpm_left.wav');
      if (r == null) return;
      print('  sos 20wpm L-only → "$r"');
      expect(r, 'SOS');
    });

    test('stereo_paris_20wpm_left (L channel only) decodes exactly', () {
      final r = _decode('$_dir/stereo_paris_20wpm_left.wav');
      if (r == null) return;
      print('  paris 20wpm L-only → "$r"');
      expect(r, 'PARIS');
    });

    test('stereo_sos_20wpm_48k_left (48 kHz, L only) decodes exactly', () {
      final r = _decode('$_dir/stereo_sos_20wpm_48k_left.wav');
      if (r == null) return;
      print('  sos 48k L-only → "$r"');
      expect(r, 'SOS');
    });

    test('stereo_sos_20wpm_right (R channel only) decodes exactly', () {
      final r = _decode('$_dir/stereo_sos_20wpm_right.wav');
      if (r == null) return;
      print('  sos 20wpm R-only → "$r"');
      expect(r, 'SOS');
    });

    test('stereo_paris_20wpm_right (R channel only) decodes exactly', () {
      final r = _decode('$_dir/stereo_paris_20wpm_right.wav');
      if (r == null) return;
      print('  paris 20wpm R-only → "$r"');
      expect(r, 'PARIS');
    });

    test('stereo_sos_20wpm_48k_right (48 kHz, R only) decodes exactly', () {
      final r = _decode('$_dir/stereo_sos_20wpm_48k_right.wav');
      if (r == null) return;
      print('  sos 48k R-only → "$r"');
      expect(r, 'SOS');
    });
  });

  // ══════════════════════════════════════════════════════════════════════════
  // 6.  Stereo vs mono equivalence
  //
  //     A stereo L+R WAV and its mono counterpart carry identical sine waves.
  //     After downmix the mono stream is identical, so decoding must produce
  //     the same text.  Any difference indicates a regression in _parseWav.
  // ══════════════════════════════════════════════════════════════════════════
  group('Stereo WAV — equivalence with mono counterparts', () {
    const pairs = <String, String>{
      'stereo_sos_20wpm':   'sos_20wpm',
      'stereo_paris_20wpm': 'paris_20wpm',
      'stereo_sos_10wpm':   'sos_10wpm',
      'stereo_sos_30wpm':   'sos_30wpm',
    };

    for (final entry in pairs.entries) {
      test('${entry.key} == ${entry.value}', () {
        final stereo = _decode('$_dir/${entry.key}.wav');
        final mono   = _decode('$_dir/${entry.value}.wav');
        if (stereo == null || mono == null) return;
        print('  stereo "$stereo"  mono "$mono"');
        expect(stereo, mono,
            reason: 'Stereo downmix must produce identical output to mono');
      });
    }
  });

  // ══════════════════════════════════════════════════════════════════════════
  // 7.  Regression guard: without downmix, stereo breaks timing
  //
  //     This group does NOT call _parseWav directly (it's private), but it
  //     validates the observable symptom: a stereo WAV passed to analyzeWav
  //     must NOT return empty.  If downmix were absent, every sample would
  //     include the interleaved second channel and timing would be doubled,
  //     producing empty output.
  // ══════════════════════════════════════════════════════════════════════════
  group('Stereo WAV — downmix regression guard', () {
    test('stereo WAV returns non-empty (downmix path is active)', () {
      final r = _decode('$_dir/stereo_sos_20wpm.wav');
      if (r == null) return;
      expect(r, isNot(isEmpty),
          reason: 'Without downmix, stereo timing doubles → empty output');
    });

    test('stereo WAV returns non-empty non-"?" content', () {
      final r = _decode('$_dir/stereo_sos_20wpm.wav');
      if (r == null) return;
      final useful = r.replaceAll('?', '').replaceAll(' ', '');
      expect(useful, isNot(isEmpty),
          reason: 'Without downmix all content is noise → only "?" markers');
    });

    test('48 kHz stereo WAV returns non-empty (sample rate read correctly)', () {
      final r = _decode('$_dir/stereo_sos_20wpm_48k.wav');
      if (r == null) return;
      expect(r, isNot(isEmpty),
          reason: 'Without correct sample rate, frame timing is wrong → empty');
    });
  });
}
